name: mapkit_snapshotter_flutter_plus
description: A flutter plugin for iOS to expose MKMapSnapshotter to your flutter project.
version: 0.0.2
repository: https://github.com/ScottMacDougall/mapkit_snapshotter_flutter_plus

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: MapkitSnapshotterFlutterPlugin
